### ISSUE TITLE
on aws linux, there is an issue with # prefix for members

### ISSUE THREAD

**Issue by filipvercauteren** [LRagji/redis-streams-broker#7]
It works fine on my macosx. however on aws linux, there is a compiler error see below.
When I remove the # prefix with __ it works.

node_modules/redis-streams-broker/asyncProcessor.js:2
    #dataProcessingHandler
    ^
SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module

**Comment by LRagji** [comment]
Can you tell me the Node version on this aws machine and your local? i assume its with node version as private members spec is implemented on later versions of node...

**Comment by filipvercauteren** [comment]
yes of course, I am using Nodejs v10.23.2 on aws and locally v12.16.1.
